name: ci

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11.0.x', '12.0.x' ]
    name: Testing on java ${{ matrix.java }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.469'

      - name: Run clean
        run: make clean

      - name: Run Clojure tests
        run: make test-clj

      - name: Run ClojureScript tests
        run: make test-cljs

      - name: Upload coverage
        run: curl -s https://codecov.io/bash | bash -s -- -c -F aFlag -f ./target/coverage/codecov.json


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: make build


  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
    steps:
      - name: Run deploy
        run: make deploy
