name: Deploying

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.469'

      - name: Run clean
        run: make clean

      - name: Run Clojure tests
        run: make test-clj

      - name: Run ClojureScript tests
        run: make test-cljs

      - name: Upload coverage
        run: curl -s https://codecov.io/bash | bash -s -- -c -F aFlag -f ./target/coverage/codecov.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run build
        run: make build

      - name: Run deploy
        run: make deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
